---
name: CI

'on': [push, pull_request]

env:
  machine_user: kitchen
  machine_pass: Pass@word1
  machine_port: 5985
  KITCHEN_LOCAL_YAML: kitchen.github.yml

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler: latest
          bundler-cache: true
      - run: |
          ruby --version
          gem info bundler
          bundle version
      - shell: powershell
        run: |
          $password = ConvertTo-SecureString $env:machine_pass -AsPlainText -Force
          New-LocalUser $env:machine_user -Password $password
          Add-LocalGroupMember -Group "Administrators" -Member $env:machine_user
      - shell: powershell
        run: >
          Set-WSManQuickConfig -Force;
          Set-WSManInstance -ResourceURI winrm/config/service
          -ValueSet @{AllowUnencrypted="true"}
      - run: |
          bundle exec kitchen verify
